import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nisarg Chauhan — AI Engineer",
  description:
    "AI Engineer focused on Computer Vision & NLP, bridging Intelligent Systems with Real-World Deployment and Community Engagement.",
  openGraph: {
    title: "Nisarg Chauhan — AI Engineer",
    description: "Building the bridge between Imagination & Intelligence. Explore my portfolio of AI, CV, and Web Projects.",
    url: "https://nisarg-portfolio.vercel.app", // Fallback/Placeholder
    siteName: "Nisarg Chauhan Portfolio",
    images: [
      {
        url: "/header.png", // Using the header image as preview
        width: 1200,
        height: 630,
        alt: "Nisarg Chauhan Portfolio Overview",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Nisarg Chauhan — AI Engineer",
    description: "AI Engineer focused on Computer Vision & NLP. Check out my work.",
    images: ["/header.png"],
  },
};

import SmoothScroll from "@/components/SmoothScroll";
import NoiseOverlay from "@/components/NoiseOverlay";
import Preloader from "@/components/Preloader";
import { LoadingProvider } from "@/context/LoadingContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoadingProvider>
          <Preloader />
          <NoiseOverlay />
          <SmoothScroll>
            {children}
          </SmoothScroll>
        </LoadingProvider>
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
